import Head from 'next/head'
import Header from '../components/Header'
import Sidebar from '../components/sidebar'
import { useContextState } from '../context/context'

export default function Home() {
  const {sidebar, setSidebar } = useContextState()

  const handleSidebar = () => {
    if(sidebar){
      setSidebar(false)
    } 
    return
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={`relative`} onClick={handleSidebar}>
        {sidebar? <div className='fixed bg-red-600'>
          <Sidebar />
        </div> : ""}
        <div>
          <Header />
        </div>
      </div>
    </>
  )
}
